### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Felipe-Hub** [ironhack-labs/lab-cleaning-numerical-data#1]
@sandrabosk 
This lab is very similar to week 1 lab, it might be a good idea to make it a bit more challenging, for example, adding some task that would require the use of interpolate to replace the outliers in 'Income'.

**Comment by ironhack-edu** [comment]
@haggarw3 can you please check this out when you grab a moment please? Thank you!

**Comment by ironhack-edu** [comment]
@Felipe-Hub In case you made some changes to fix this issue during your cohort, please make a PR so we can close this issue. Thank you.
